global:
  enabled_helm: true

deploymentRuntimeConfig:
  enabled: true
  metadata:
    name: "helm-runtime-config"
    annotations: {}
    labels: {}
  spec:
    deploymentTemplate:
      spec:
        selector: {}
        template: {}
    serviceAccountTemplate:
      metadata:
        annotations: {}
        labels: {}
        name: helm-provider

provider:
  enabled: true
  metadata:
    name: "helm-provider"
    annotations: {}
    labels: {}
  package:
    registry: xpkg.upbound.io/crossplane-contrib/provider-helm
    version: "v0.16.0"

providerConfig:
  enabled: true
  metadata:
    name: "default"
    annotations: {}
    labels: {}
  spec:
    credentials:
      source: InjectedIdentity

clusterRoleBinding:
  enabled: true
  metadata:
    name: "helm-provider"
    annotations: {}
    labels: {}
  roleRef:
    kind: ClusterRole
    name: cluster-admin
    apiGroup: rbac.authorization.k8s.io
