apiVersion: kubernetes.example.com/v1alpha1
kind: AksClusterClaim
metadata:
  name: airlift-oow-cluster
  annotations:
    crossplane.io/external-name: airlift-oow-cluster
    argocd.argoproj.io/sync-wave: "3"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  location: "North Europe"
  aks:
    defaultNodePool:
      name: system
      vmSize: Standard_D2s_v3
      enableAutoScaling: true
      nodeCount: 1
      minCount: 1
      maxCount: 20
      maxPods: 30
      nodeLabels:
        mode: system
      onlyCriticalAddonsEnabled: false
      osDiskSizeGb: 128
      osDiskType: Managed
    roleBasedAccessControlEnabled: true
    oidcIssuerEnabled: true
    workloadIdentityEnabled: true
    privateClusterEnabled: false
    azureActiveDirectoryRoleBasedAccessControl:
      - adminGroupObjectIds:
          - 80ee8d91-a157-4fe3-acf0-e095b160af60
        azureRbacEnabled: true
        managed: true
    azurePolicyEnabled: true
    networkProfile:    
      - networkPlugin: azure
        networkPolicy: azure
        outboundType: loadBalancer
        dnsServiceIp: 172.16.0.10
        serviceCidr: 172.16.0.0/16
    workloadAutoscalerProfile:
      - kedaEnabled: true
        verticalPodAutoscalerEnabled: true
    tags:
      environment: Test
      provisionedBy: Crossplane
  userNodePool:
    name: user
    vmSize: Standard_B2s
    enableAutoScaling: true
    nodeCount: 1
    minCount: 1
    maxCount: 20
    maxPods: 30
    nodeLabels:
      mode: user
    osDiskSizeGb: 128
    osDiskType: Managed
    osSku: AzureLinux
    osType: Linux
  subnet:
    name: MainSubnet
    privateEndpointNetworkPoliciesEnabled: true
    privateLinkServiceNetworkPoliciesEnabled: false
    addressPrefixes:
      - 10.0.0.0/16
  virtualNetwork:
    addressSpace:
      - 10.0.0.0/8
    tags:
      environment: Test
      provisionedBy: Crossplane   