global:
  enabled_azure_upbound: true

deploymentRuntimeConfig:
  enabled: false
  metadata:
    name: "upbound-azure-runtime-config"
    role_arn: ""
    annotations: {}
    labels:
      app.kubernetes.io/managed-by: Helm
  spec:
    deploymentTemplate:
      spec:
        selector: {}
        template:
          metadata:
            annotations: {}
            labels: 
              azure.workload.identity/use: true
          spec:
            containers:
              - name: package-runtime
                args:
                - --debug
            securityContext:
              fsGroup: 2000
    serviceAccountTemplate:
      metadata:
        annotations: {}
        labels:
        name: azure-provider

provider:
  enabled: true
  metadata:
    annotations: {}
    labels:
      app.kubernetes.io/managed-by: Helm
  package:
    registry: xpkg.upbound.io/upbound
    version: v0.42.0

providerConfig:
  enabled: true
  metadata:
    name: default
    annotations: {}
    labels:
      app.kubernetes.io/managed-by: Helm
  spec:
    credentials:
      source: Secret
      secretRef:
        namespace: crossplane-system
        name: azure-secret
        key: creds
    
providers:
- network
- compute
- storage
- authorization
- containerservice
- containerregistry
- keyvault
- operationalinsights
- insights
- managedidentity
- resources