namespace: oow-test-cluster-cluster-stage

resources:
  - ../base
  - namespace.yaml 
  
patches:
- path: cluster-claim.yaml 
  target:
    group: kubernetes.example.com
    version: v1alpha1
    kind: AksClusterClaim
    name: oow-test-cluster-cluster-stage
- patch: |-
    - op: replace
      path: /metadata/name
      value: oow-test-cluster-cluster-stage 
  target:
    kind: AksClusterClaim   