
apiVersion: kubernetes.example.com/v1alpha1
kind: AksClusterClaim
metadata:
  name: my-app-cluster
  annotations:
    crossplane.io/external-name: my-app-cluster-dev  
spec:
  writeConnectionSecretToRef:
    name: my-app-cluster-dev-secret
  location: "North Europe"
  aks:
    adminUser: 8e574c9a-1523-4d37-adc5-501f0b1488d5
    tags:
      environment: dev
  virtualNetwork:
    tags:
      environment: dev   
