
apiVersion: kubernetes.example.com/v1alpha1
kind: AksClusterClaim
metadata:
  name: ${{ values.name }}-cluster
  annotations:
    crossplane.io/external-name: ${{ values.name }}-cluster-dev  
spec:
  writeConnectionSecretToRef:
    name: my-app-cluster-dev-secret
  location: "North Europe"
  aks:
    adminUser: ${{ values.adminUser }}
    tags:
      environment: dev
  virtualNetwork:
    tags:
      environment: dev   
