namespace: ${{ values.name }}-cluster-dev

resources:
  - ../base
  - namespace.yaml

patches:
- path: cluster-claim.yaml 
  target:
    group: kubernetes.example.com
    version: v1alpha1
    kind: AksClusterClaim
    name: ${{ values.name }}-cluster
- patch: |-
    - op: replace
      path: /metadata/name
      value: ${{ values.name }}-cluster-dev  
  target:
    kind: AksClusterClaim     