{{- if and .Values.global.enabled_kubernetes .Values.clusterRoleBinding.enabled }}
{{- with .Values.clusterRoleBinding }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .metadata.name }}
  {{- if .metadata.annotations }}
  annotations:
    {{- range $key, $value := .metadata.annotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
  {{- end }}
  {{- if .metadata.labels }}
  labels:
    {{- range $key, $value := .metadata.labels }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
  {{- end }}
subjects:
  - kind: ServiceAccount
    name: {{ $.Values.deploymentRuntimeConfig.spec.serviceAccountTemplate.metadata.name }}
    namespace: {{ $.Release.Namespace  }}
roleRef:
  {{- .roleRef | toYaml | nindent 2 }}
{{- end }}
{{- end }}