apiVersion: v1
kind: Service
metadata:
  name: {{ include "backstagechart.fullname" . }}
  namespace: {{ .Values.namespace }} 
  labels:
    {{- include "backstagechart.labels" . | nindent 4 }}
  annotations:
    {{- with .Values.service.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: https
      port: 443
      targetPort: 7007
  selector:
    {{- include "backstagechart.selectorLabels" . | nindent 4 }}
