
apiVersion: kubernetes.example.com/v1alpha1
kind: AksClusterClaim
metadata:
  name: my-app-cluster
  annotations:
    crossplane.io/external-name: my-app-cluster-stage  
spec:
  location: "EastUs"
  aks:
    tags:
      environment: stage
  virtualNetwork:
    addressSpace:
      - 10.0.0.0/8
    tags:
      environment: stage
  writeConnectionSecretToRef:
    name: my-app-cluster-stage-secret      