
apiVersion: kubernetes.example.com/v1alpha1
kind: AksClusterClaim
metadata:
  name: my-app-cluster
  annotations:
    crossplane.io/external-name: my-app-cluster-stage  
spec:
  writeConnectionSecretToRef:
    name: my-app-cluster-stage-secret    
  location: "EastUs"
  aks:
    adminUser: 8e574c9a-1523-4d37-adc5-501f0b1488d5
    tags:
      environment: stage
  virtualNetwork:
    tags:
      environment: stage     
  