global:
  enabled_kubernetes: true

deploymentRuntimeConfig:
  enabled: true
  metadata:
    name: "kubernetes-runtime-config"
    annotations: {}
    labels: {}
  spec:
    deploymentTemplate:
      spec:
        selector: {}
        template: {}
    serviceAccountTemplate:
      metadata:
        annotations: {}
        labels: {}
        name: kubernetes-provider

provider:
  enabled: true
  metadata:
    name: "kubernetes-provider"
    annotations: {}
    labels: {}
  package:
    registry: xpkg.upbound.io/crossplane-contrib/provider-kubernetes
    version: "v0.10.0"

providerConfig:
  enabled: true
  metadata:
    name: "default"
    annotations: {}
    labels: {}
  spec:
    credentials:
      source: InjectedIdentity

clusterRoleBinding:
  enabled: true
  metadata:
    name: "kubernetes-provider"
    annotations: {}
    labels: {}
  roleRef:
    kind: ClusterRole
    name: cluster-admin
    apiGroup: rbac.authorization.k8s.io
